name: Build and Deploy
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.12.0'
      
      - name: Install Project Dependencies
        run: npm ci
      
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@3.14.0
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public
      
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.PORT }}
         script: cd /marts/pocket-audio; git pull; hugo; cp -r ./public/* /public_html/.; rm -rf ./public
